on:
  push:
    branches:
      - main
      - release/*
name: Build and Test Flutter App

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # Or specify a specific version

      # Run Flutter commands
      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test

      # Optionally build the app (e.g., for Android or iOS)
      - name: Build APK (Android)
        run: flutter build apk --release

      # If targeting iOS, use the following step (requires macOS)
      - name: Build iOS (requires macOS)
        if: matrix.os == 'macOS-latest'
        run: flutter build ios --release
